// Server-only MTN MoMo Collections helpers. Never import from client code.
import { Buffer } from "node:buffer";

const TARGET_ENV = () => process.env.MOMO_TARGET_ENVIRONMENT || "sandbox";
const BASE_URL = () =>
  TARGET_ENV() === "sandbox"
    ? "https://sandbox.momodeveloper.mtn.com"
    : "https://proxy.momoapi.mtn.com";

function requireEnv() {
  const subKey = process.env.MOMO_SUBSCRIPTION_KEY;
  const apiUser = process.env.MOMO_API_USER;
  const apiKey = process.env.MOMO_API_KEY;
  if (!subKey || !apiUser || !apiKey) {
    throw new Error(
      "MoMo not configured. Add MOMO_SUBSCRIPTION_KEY, MOMO_API_USER and MOMO_API_KEY in backend secrets.",
    );
  }
  return { subKey, apiUser, apiKey };
}

let cachedToken: { token: string; expiresAt: number } | null = null;

export async function getAccessToken(): Promise<string> {
  if (cachedToken && cachedToken.expiresAt > Date.now() + 60_000) {
    return cachedToken.token;
  }
  const { subKey, apiUser, apiKey } = requireEnv();
  const auth = Buffer.from(`${apiUser}:${apiKey}`).toString("base64");
  const res = await fetch(`${BASE_URL()}/collection/token/`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${auth}`,
      "Ocp-Apim-Subscription-Key": subKey,
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`MoMo token error ${res.status}: ${body}`);
  }
  const data = (await res.json()) as { access_token: string; expires_in: number };
  cachedToken = {
    token: data.access_token,
    expiresAt: Date.now() + data.expires_in * 1000,
  };
  return data.access_token;
}

export type RequestToPayInput = {
  referenceId: string; // UUID v4 generated by caller
  externalId: string;
  amount: number;
  currency?: string;
  phone: string; // MSISDN e.g. 2507XXXXXXXX (no +)
  payerMessage?: string;
  payeeNote?: string;
};

export async function requestToPay(input: RequestToPayInput): Promise<void> {
  const { subKey } = requireEnv();
  const token = await getAccessToken();
  const callbackHost = process.env.MOMO_CALLBACK_HOST;
  const headers: Record<string, string> = {
    Authorization: `Bearer ${token}`,
    "X-Reference-Id": input.referenceId,
    "X-Target-Environment": TARGET_ENV(),
    "Ocp-Apim-Subscription-Key": subKey,
    "Content-Type": "application/json",
  };
  if (callbackHost) headers["X-Callback-Url"] = `https://${callbackHost}/api/public/momo/callback`;

  const body = {
    amount: String(Math.round(input.amount)),
    currency: input.currency || (TARGET_ENV() === "sandbox" ? "EUR" : "RWF"),
    externalId: input.externalId,
    payer: { partyIdType: "MSISDN", partyId: input.phone.replace(/\D/g, "") },
    payerMessage: (input.payerMessage || "Payment").slice(0, 160),
    payeeNote: (input.payeeNote || "Order").slice(0, 160),
  };

  const res = await fetch(`${BASE_URL()}/collection/v1_0/requesttopay`, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });
  if (res.status !== 202) {
    const text = await res.text();
    throw new Error(`requestToPay failed ${res.status}: ${text}`);
  }
}

export type PaymentStatus = {
  status: "PENDING" | "SUCCESSFUL" | "FAILED";
  reason?: string;
  financialTransactionId?: string;
  raw: unknown;
};

export async function getPaymentStatus(referenceId: string): Promise<PaymentStatus> {
  const { subKey } = requireEnv();
  const token = await getAccessToken();
  const res = await fetch(`${BASE_URL()}/collection/v1_0/requesttopay/${referenceId}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      "X-Target-Environment": TARGET_ENV(),
      "Ocp-Apim-Subscription-Key": subKey,
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`status check failed ${res.status}: ${text}`);
  }
  const data = (await res.json()) as {
    status: "PENDING" | "SUCCESSFUL" | "FAILED";
    reason?: string | { code?: string; message?: string };
    financialTransactionId?: string;
  };
  const reason =
    typeof data.reason === "string"
      ? data.reason
      : data.reason && (data.reason.message || data.reason.code);
  return {
    status: data.status,
    reason: reason || undefined,
    financialTransactionId: data.financialTransactionId,
    raw: data,
  };
}
