/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestQuotationRouteImport } from './routes/request-quotation'
import { Route as RequestProductRouteImport } from './routes/request-product'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AdminTechniciansRouteImport } from './routes/admin.technicians'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminMomoRouteImport } from './routes/admin.momo'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as QuoteTokenInvoiceRouteImport } from './routes/quote.$token.invoice'
import { Route as AdminMomoIdRouteImport } from './routes/admin.momo.$id'
import { Route as AuthenticatedAdminQuotationsRouteImport } from './routes/_authenticated/admin.quotations'
import { Route as ApiPublicCronBookingsTickRouteImport } from './routes/api/public/cron/bookings-tick'
import { Route as AuthenticatedAdminQuotationsIdRouteImport } from './routes/_authenticated/admin.quotations.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuotationRoute = RequestQuotationRouteImport.update({
  id: '/request-quotation',
  path: '/request-quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestProductRoute = RequestProductRouteImport.update({
  id: '/request-product',
  path: '/request-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/admin/technicians',
  path: '/admin/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMomoRoute = AdminMomoRouteImport.update({
  id: '/admin/momo',
  path: '/admin/momo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const QuoteTokenInvoiceRoute = QuoteTokenInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => QuoteTokenRoute,
} as any)
const AdminMomoIdRoute = AdminMomoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMomoRoute,
} as any)
const AuthenticatedAdminQuotationsRoute =
  AuthenticatedAdminQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronBookingsTickRoute =
  ApiPublicCronBookingsTickRouteImport.update({
    id: '/api/public/cron/bookings-tick',
    path: '/api/public/cron/bookings-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminQuotationsIdRoute =
  AuthenticatedAdminQuotationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminQuotationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRouteWithChildren
  '/request-product': typeof RequestProductRoute
  '/request-quotation': typeof RequestQuotationRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technicians': typeof TechniciansRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/momo': typeof AdminMomoRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/products/$id': typeof ProductsIdRoute
  '/quote/$token': typeof QuoteTokenRouteWithChildren
  '/admin/quotations': typeof AuthenticatedAdminQuotationsRouteWithChildren
  '/admin/momo/$id': typeof AdminMomoIdRoute
  '/quote/$token/invoice': typeof QuoteTokenInvoiceRoute
  '/admin/quotations/$id': typeof AuthenticatedAdminQuotationsIdRoute
  '/api/public/cron/bookings-tick': typeof ApiPublicCronBookingsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRouteWithChildren
  '/request-product': typeof RequestProductRoute
  '/request-quotation': typeof RequestQuotationRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technicians': typeof TechniciansRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/momo': typeof AdminMomoRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/products/$id': typeof ProductsIdRoute
  '/quote/$token': typeof QuoteTokenRouteWithChildren
  '/admin/quotations': typeof AuthenticatedAdminQuotationsRouteWithChildren
  '/admin/momo/$id': typeof AdminMomoIdRoute
  '/quote/$token/invoice': typeof QuoteTokenInvoiceRoute
  '/admin/quotations/$id': typeof AuthenticatedAdminQuotationsIdRoute
  '/api/public/cron/bookings-tick': typeof ApiPublicCronBookingsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRouteWithChildren
  '/request-product': typeof RequestProductRoute
  '/request-quotation': typeof RequestQuotationRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technicians': typeof TechniciansRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/momo': typeof AdminMomoRouteWithChildren
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/products/$id': typeof ProductsIdRoute
  '/quote/$token': typeof QuoteTokenRouteWithChildren
  '/_authenticated/admin/quotations': typeof AuthenticatedAdminQuotationsRouteWithChildren
  '/admin/momo/$id': typeof AdminMomoIdRoute
  '/quote/$token/invoice': typeof QuoteTokenInvoiceRoute
  '/_authenticated/admin/quotations/$id': typeof AuthenticatedAdminQuotationsIdRoute
  '/api/public/cron/bookings-tick': typeof ApiPublicCronBookingsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/products'
    | '/request-product'
    | '/request-quotation'
    | '/search'
    | '/sitemap.xml'
    | '/technicians'
    | '/wishlist'
    | '/admin'
    | '/admin/momo'
    | '/admin/requests'
    | '/admin/technicians'
    | '/products/$id'
    | '/quote/$token'
    | '/admin/quotations'
    | '/admin/momo/$id'
    | '/quote/$token/invoice'
    | '/admin/quotations/$id'
    | '/api/public/cron/bookings-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/products'
    | '/request-product'
    | '/request-quotation'
    | '/search'
    | '/sitemap.xml'
    | '/technicians'
    | '/wishlist'
    | '/admin'
    | '/admin/momo'
    | '/admin/requests'
    | '/admin/technicians'
    | '/products/$id'
    | '/quote/$token'
    | '/admin/quotations'
    | '/admin/momo/$id'
    | '/quote/$token/invoice'
    | '/admin/quotations/$id'
    | '/api/public/cron/bookings-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/products'
    | '/request-product'
    | '/request-quotation'
    | '/search'
    | '/sitemap.xml'
    | '/technicians'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/admin/momo'
    | '/admin/requests'
    | '/admin/technicians'
    | '/products/$id'
    | '/quote/$token'
    | '/_authenticated/admin/quotations'
    | '/admin/momo/$id'
    | '/quote/$token/invoice'
    | '/_authenticated/admin/quotations/$id'
    | '/api/public/cron/bookings-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  FaqRoute: typeof FaqRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RequestProductRoute: typeof RequestProductRoute
  RequestQuotationRoute: typeof RequestQuotationRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechniciansRoute: typeof TechniciansRoute
  WishlistRoute: typeof WishlistRoute
  AdminMomoRoute: typeof AdminMomoRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  QuoteTokenRoute: typeof QuoteTokenRouteWithChildren
  ApiPublicCronBookingsTickRoute: typeof ApiPublicCronBookingsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quotation': {
      id: '/request-quotation'
      path: '/request-quotation'
      fullPath: '/request-quotation'
      preLoaderRoute: typeof RequestQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-product': {
      id: '/request-product'
      path: '/request-product'
      fullPath: '/request-product'
      preLoaderRoute: typeof RequestProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/admin/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/momo': {
      id: '/admin/momo'
      path: '/admin/momo'
      fullPath: '/admin/momo'
      preLoaderRoute: typeof AdminMomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/quote/$token/invoice': {
      id: '/quote/$token/invoice'
      path: '/invoice'
      fullPath: '/quote/$token/invoice'
      preLoaderRoute: typeof QuoteTokenInvoiceRouteImport
      parentRoute: typeof QuoteTokenRoute
    }
    '/admin/momo/$id': {
      id: '/admin/momo/$id'
      path: '/$id'
      fullPath: '/admin/momo/$id'
      preLoaderRoute: typeof AdminMomoIdRouteImport
      parentRoute: typeof AdminMomoRoute
    }
    '/_authenticated/admin/quotations': {
      id: '/_authenticated/admin/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AuthenticatedAdminQuotationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/bookings-tick': {
      id: '/api/public/cron/bookings-tick'
      path: '/api/public/cron/bookings-tick'
      fullPath: '/api/public/cron/bookings-tick'
      preLoaderRoute: typeof ApiPublicCronBookingsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/quotations/$id': {
      id: '/_authenticated/admin/quotations/$id'
      path: '/$id'
      fullPath: '/admin/quotations/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuotationsRoute
    }
  }
}

interface AuthenticatedAdminQuotationsRouteChildren {
  AuthenticatedAdminQuotationsIdRoute: typeof AuthenticatedAdminQuotationsIdRoute
}

const AuthenticatedAdminQuotationsRouteChildren: AuthenticatedAdminQuotationsRouteChildren =
  {
    AuthenticatedAdminQuotationsIdRoute: AuthenticatedAdminQuotationsIdRoute,
  }

const AuthenticatedAdminQuotationsRouteWithChildren =
  AuthenticatedAdminQuotationsRoute._addFileChildren(
    AuthenticatedAdminQuotationsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminQuotationsRoute: typeof AuthenticatedAdminQuotationsRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminQuotationsRoute:
    AuthenticatedAdminQuotationsRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface AdminMomoRouteChildren {
  AdminMomoIdRoute: typeof AdminMomoIdRoute
}

const AdminMomoRouteChildren: AdminMomoRouteChildren = {
  AdminMomoIdRoute: AdminMomoIdRoute,
}

const AdminMomoRouteWithChildren = AdminMomoRoute._addFileChildren(
  AdminMomoRouteChildren,
)

interface QuoteTokenRouteChildren {
  QuoteTokenInvoiceRoute: typeof QuoteTokenInvoiceRoute
}

const QuoteTokenRouteChildren: QuoteTokenRouteChildren = {
  QuoteTokenInvoiceRoute: QuoteTokenInvoiceRoute,
}

const QuoteTokenRouteWithChildren = QuoteTokenRoute._addFileChildren(
  QuoteTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  FaqRoute: FaqRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RequestProductRoute: RequestProductRoute,
  RequestQuotationRoute: RequestQuotationRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechniciansRoute: TechniciansRoute,
  WishlistRoute: WishlistRoute,
  AdminMomoRoute: AdminMomoRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminTechniciansRoute: AdminTechniciansRoute,
  QuoteTokenRoute: QuoteTokenRouteWithChildren,
  ApiPublicCronBookingsTickRoute: ApiPublicCronBookingsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
